:sectnums: |,all|
=== Conclusions

==== Desviacions el la planificació

En general, hem planificat les tasques intentant arribar a les màximes hores disponibles de treball per a cada setmana, no obstant això, al no tenir experiència a l'hora de la planificació, van haver tasques que vam planificat per a més hores de les que necessitaven, i altres, que al contrari, vam pensar que serien més ràpides i senzilles de realitzar, pero, ens van portar més temps de l'imaginat.

Creiem que per aquesta raó, al no haver realitzat bé la planificació, ens van faltar hores per a fer algunes tasques, com la missatgeria interna, o algunes proves unitaries.

En adonar-nos que ens faltava temps per implementar una nova funcionalitat, vam decidir acabar i polir les funcionalitats ja implementades.


==== Aportacions del projecte

Gràcies a aquest projecte, ens hem familiaritzat amb el _framework_ *Laravel* i après a treballar amb *ORM* (Object Relational Mapping), en aquest cas *Eloquent*, que és l'ORM que integra Laravel.