# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "javamariadb"
  config.vm.define "javamariadb"
  config.vm.network "private_network", ip: "172.16.0.100"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb|
	vb.name = "Marketplace_grup5" 
    vb.memory = "512"
    vb.cpus = 1
  end
end