Vagrant.configure("2") do |config|

  config.vm.define "api" do |api|
    api.vm.box = "ubuntu/focal64"
    api.vm.network "private_network", ip: "172.16.50.60"
    api.vm.synced_folder "./api", "/home/vagrant/api"
    api.vm.provision "shell", path: "setupApi.sh"
    api.vm.define "vagrantApi"
  end

  config.vm.define "botiga" do |botiga|
    botiga.vm.box = "ubuntu/focal64"
    botiga.vm.network "private_network", ip: "172.16.50.50"
    botiga.vm.synced_folder "./botiga", "/home/vagrant/botiga/"
    botiga.vm.provision "shell", path: "setupTenda.sh"
    botiga.vm.define "vagrantBotiga"
  end
  
end