Vagrant.configure("2") do |config|

  config.vm.define "tenda" do |tenda|
    tenda.vm.box = "ubuntu/focal64"
    tenda.vm.network "private_network", ip: "172.16.50.50"
    tenda.vm.synced_folder "./tenda", "/var/www/html"
    tenda.vm.provision "shell", path: "setupTenda.sh"
    tenda.vm.define "vagrantTenda"
  end

  config.vm.define "api" do |api|
    api.vm.box = "ubuntu/focal64"
    api.vm.network "private_network", ip: "172.16.50.60"
    api.vm.synced_folder "./api", "/var/www/html"
    api.vm.provision "shell", path: "setupApi.sh"
    api.vm.define "vagrantApi"
  end
end